-- 코드를 입력하세요
-- 2022년 3월의 오프라인/온라인 상품 판매 데이터
-- 날짜, 상품ID, 유저ID, 판매량을 출력
-- OFFLINE_SALE 테이블의 판매 데이터의 USER_ID 값은 NULL 로 표시
-- 결과는 판매일을 기준으로 오름차순 정렬해주시고 판매일이 같다면 상품 ID를 기준으로 오름차순, 상품ID까지 같다면 유저 ID를 기준으로 오름차순 정렬

-- SELECT *
--     FROM ONLINE_SALE 
--     WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203'
-- SELECT *
-- FROM TA A
-- LEFT JOIN TB B ON A.PRODUCT_ID = B.PRODUCT_ID


SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT AS SALES_AMOUNT
FROM (SELECT *
    FROM ONLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203'
UNION ALL
    SELECT OFFLINE_SALE_ID, NULL, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203' )
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;