-- 코드를 입력하세요
-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 
--2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서
--자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력
--결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 자동차 종류를 기준으로 오름차순 정렬, 자동차 종류까지 같은 경우 자동차 ID를 기준으로 내림차순 정렬


SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE*30*(1-C.DISCOUNT_RATE/100) FEE
FROM (SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE='세단' OR CAR_TYPE='SUV') A JOIN 
(SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY D
 WHERE NOT EXISTS(
     SELECT 1 
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY E
     WHERE D.CAR_ID = E.CAR_ID 
        AND TO_CHAR(E.START_DATE, 'YYYYMMDD') <= '20221130' 
        AND TO_CHAR(E.END_DATE, 'YYYYMMDD') >= '20221101')) B  ON A.CAR_ID = B.CAR_ID
JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE='30일 이상') C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.DAILY_FEE*30*(1-C.DISCOUNT_RATE/100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;