-- 코드를 입력하세요
SELECT CAR_ID , ROUND(AVG(DATEDIFF(END_DATE ,START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(DATEDIFF(END_DATE ,START_DATE)+1),1) >= 7
ORDER BY ROUND(AVG(DATEDIFF(END_DATE ,START_DATE)+1),1) DESC, CAR_ID DESC;

# SELECT CAR_ID, START_DATE, END_DATE, DATEDIFF(END_DATE,START_DATE)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID DESC;