-- 코드를 작성해주세요
--  물고기 종류 별로 가장 큰 물고기
--  ID, 물고기 이름, 길이를
-- 물고기의 ID 컬럼명은 ID, 이름 컬럼명은 FISH_NAME, 길이 컬럼명은 LENGTH
-- 결과는 물고기의 ID에 대해 오름차순 정렬

SELECT A.ID ID, B.FISH_NAME FISH_NAME, A.LENGTH LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FISH_TYPE = A.FISH_TYPE)
ORDER BY A.ID ASC;